### ISSUE TITLE
No bridge/blind state fetch error/Plugin seems to be expecting server to return a dictionary or array?

### ISSUE THREAD

**Issue by name99-org** [apexad/homebridge-mysmartblinds-bridge#15] opened 2020-06-03 06:03 UTC
**Bug or issue information**
> Include as much detail as possible including what is happening and what is expected.

I've installed the MySmartBlinds plugin to my HomeKit setup and right away, in the startup process, it reports:

[6/2/2020, 10:58:53 PM] [MySmartBlindsBridge] Error during blind state fetch Error: Stairs South: Cannot read property '0' of null
    at /usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/index.js:162:31
    at tryCatcher (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
Setup Payload:
X-HM://0024AOLL3NI9A

I'm no JS expert, but if I HAD to guess, my guess would be that perhaps the code is implicitly assuming multiple items where there is only one item?
My current MySmartBlinds system is very simple: one tilt blinds (called South) in one room (called Stairs). 
The blinds are connected to the app and appear to work correctly; likewise HomeBridge as a whole appears to work correctly. 

**Homebridge setup information**
> Include if you are running homebridge directly, using HOOBS, etc...  
> Include details about your configuration if needed, but do not include any email address or password.  
> Include node version, if known.
I'm running HomeBridge on a mac mini; 
OS version         macOS Catalina
Homebridge version 1.1.0
node.js version v12.18.0
npm version      v6.14.4

**Logs**
> Include logs here.  Be sure to remove any user identifiable information.

**Comment by name99-org** [comment] 2020-06-03 06:10
OK, after looking at the code I guess I understand the issue. 
Your plugin communicates with a MySmartBlinds BRIDGE, not directly with the blinds...
You may think this is dumb, but I was not aware of this, and I think the same will be true of other users who just do a search for MySmartBlinds, install the plugin, and go. 
Might I suggest that you handle this by providing an informative error message in response to this error condition?

**Comment by apexad** [comment] 2020-06-03 14:33
Duplicate of #11 and turning on the `allow_debug` config option already gives the error message:
```bash
[4/18/2020, 1:57:52 PM] [MySmartBlindsBridge] DEBUG GetBlindsState {
  data: { blindsState: null },
  errors: [
    { message: 'No bridges found', locations: [Array], path: [Array] }
  ]
}
```
As I mentioned in #11 you should try https://www.npmjs.com/package/homebridge-mysmartblinds as a possible solution for now.

Otherwise I am workin on converting this plugin to a dynamic platform (current a static platform, see #13 for more information about this).  I'm hoping to get this done with the next week or so.  

After that, I plan to look into doing the following:

1. Better evaluate the **No bridges found** error message and display it even when `allow_debug` is not turned on
2. Print out a list of blinds so that they could be easily added to https://www.npmjs.com/package/homebridge-mysmartblinds
3. Fall back to bluetooth if no bridge is present (integrating https://www.npmjs.com/package/homebridge-mysmartblinds)

Because of this, I will re-open this thread until at least one of those above is done.

**Comment by apexad** [comment] 2020-06-03 15:16
I also decided to add a note about the bridge to the top of the settings window if using [homebridge-config-ui-x](https://www.npmjs.com/package/homebridge-config-ui-x) now.  Hopefully this well help.

<img width="796" alt="Screen Shot 2020-06-03 at 8 14 36 AM" src="https://user-images.githubusercontent.com/1437332/83654764-66562d80-a572-11ea-9f09-10950a7dabf9.png">

I'll still keep this issue open for now though until I address the 3 thing listed in my previous comment.

**Comment by name99-org** [comment] 2020-06-03 15:56
Hi Alex, thanks for the responses.

BTW I switched on allow_debug but that did not show the sort of error message you suggest. Now I am using HomeBridge on macOS, so I've no idea where the combination of HomeBridge+node.js is routing stdout... I assumed what I saw in the Homebridge browser window included stdout, but perhaps it only includes material specifically written to some sort of "user visible log"? Either way, this may be another issue you want to consider as you harden the plugin -- where stdout (and thus debugging messages) go on other platforms.

But I think your final solution, this one, is great. It makes the issue a lot clearer :-)


Your general plan going forward sounds very promising. The difficult thing about using  https://www.npmjs.com/package/homebridge-mysmartblinds <https://www.npmjs.com/package/homebridge-mysmartblinds> is that there is so much finicky manual configuration required. If you can automate that to some extent (ie use your existing code to build all those control URLs behind the scenes) while ALSO using bluetooth to communicate with individual blinds as necessary, that would be awesome! Best of luck.

**Comment by apexad** [comment] 2020-06-03 17:48
If you are seeing other homebridge logs in the ui, you should have seen that error there too. Using the standard homebridge logger.

**Closed** 2020-06-04 08:26 UTC
Labels: bug, duplicate, enhancement

**Comment by apexad** [comment] 2020-06-04 08:33
So, a few things out after doing some research...
The Mac address and key I get from the API is labeled as `encoded` and I don't think it can be directly inserted into https://www.npmjs.com/package/homebridge-mysmartblinds without first decoding it. I'm not quite sure how I would decode it. That being said, I did correct the logs such that it will definitely output both (encoded) values now that may be of use.

Aslo, **I have made the decision not support bluetooth control of devices**. The biggest reason is that if I were to do so, first off I would be duplicating the work that is already done in https://www.npmjs.com/package/homebridge-mysmartblinds but most importantly, I would be allowing users to operate their blinds as If they had the bridge, when the actually do not.  Generally speaking it is my belief that companies let plugins like this slide because we actually benefit them by directing consumers to their products which is ultimately a win for them.  If I were to directly replace a piece of hardware they sell with a free solution, I open myself up to potential litigation.

So, with that said, v1.5.3 will be rebased shortly and contain the corrected logging, but I don't plan on doing anymore with this issue, so this is why I closed it.
